DROP DATABASE IF EXISTS sharktank_db;
CREATE DATABASE sharktank_db;

\c sharktank_db;

CREATE TABLE pitches (
 id SERIAL PRIMARY KEY,
 Season_Number VARCHAR(255),
Season_Start VARCHAR(255),	
Season_End VARCHAR(255),	
Episode_Number VARCHAR(255),	
Pitch_Number VARCHAR(255),	
Original_Air_Date VARCHAR(255),	
Startup_Name VARCHAR(255),	
Industry VARCHAR(255),	
Business_Description VARCHAR(255),	
Pitchers_Gender VARCHAR(255),
Pitchers_City VARCHAR(255),	
Pitchers_State VARCHAR(255),	
Pitchers_Average_Age VARCHAR(255),	
Entrepreneur_Names VARCHAR(255),	
Company_Website VARCHAR(255),	
Multiple_Entrepreneurs VARCHAR(255),	
US_Viewership VARCHAR(255),	
Original_Ask_Amount VARCHAR(255),	
Original_Offered_Equity VARCHAR(255),	
Valuation_Requested VARCHAR(255),
Got_Deal VARCHAR(255),	
Total_Deal_Amount VARCHAR(255),	
Total_Deal_Equity VARCHAR(255),	
Deal_Valuation VARCHAR(255),	
Number_of_sharks_in_deal VARCHAR(255),	
Investment_Amount_Per_Shark VARCHAR(255),	
Equity_Per_Shark VARCHAR(255),	
Royalty_Deal VARCHAR(255),	
Loan VARCHAR(255),	
Barbara_Corcoran_Investment_Amount VARCHAR(255),
Barbara_Corcoran_Investment_Equity VARCHAR(255),		
Mark_Cuban_Investment_Amount VARCHAR(255),	
Mark_Cuban_Investment_Equity VARCHAR(255),	
Lori_Greiner_Investment_Amount VARCHAR(255),	
Lori_Greiner_Investment_Equity VARCHAR(255),	
Robert_Herjavec_Investment_Amount VARCHAR(255),	
Robert_Herjavec_Investment_Equity VARCHAR(255),	
Daymond_John_Investment_Amount VARCHAR(255),	
Daymond_John_Investment_Equity VARCHAR(255),	
Kevin_O_Leary_Investment_Amount VARCHAR(255),	
Kevin_O_Leary_Investment_Equity VARCHAR(255),	
Guest_Investment_Amount VARCHAR(255),	
Guest_Investment_Equity VARCHAR(255),	
Guest_Name VARCHAR(255),	
Barbara_Corcoran_Present VARCHAR(255),	
Mark_Cuban_Present VARCHAR(255),	
Lori_Greiner_Present VARCHAR(255),	
Robert_Herjavec_Present VARCHAR(255),	
Daymond_John_Present VARCHAR(255),	
Kevin_O_Leary_Present VARCHAR(255)
);